name: fungal_kg
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cpython=3.10.19
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - filelock=3.20.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gsl=2.7
  - hmmer=3.4
  - icu=78.1
  - jinja2=3.1.6
  - ld_impl_linux-64=2.45
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openmpi=4.1.6
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.19
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - readline=8.3
  - setuptools=80.9.0
  - sympy=1.14.0
  - tbb=2021.13.0
  - tk=8.6.13
  - torchtriton=3.1.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wheel=0.45.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - fair-esm==2.0.0
      - neo4j==6.0.3
      - pytz==2025.2
prefix: /home/funda/miniconda/envs/fungal_kg
